safe:        false
port:        4000
baseurl:     /
url:         http://tetedulinuxien.fr

author:      Ypnose
title:       Dans la Tête du Linuxien
description: Les péripéties d'un libriste convaincu et passionné de 23 ans.

source:      .
destination: ./_site
layouts:     ./_layouts

pygments:    false
markdown:    kramdown
permalink:   /:year/:month/:title/

exclude:     ['CNAME','README','design_old','*.BAK']
